jarsigner -keystore myKeys -storepass pakistan lib/antlr-2.7.7.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/aopalliance-1.0.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/asm-3.1.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/cglib-2.2.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/classmate-0.5.4.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/commons-collections-3.2.1.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/commons-logging-1.1.1.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/dom4j-1.6.1.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/hibernate-commons-annotations-4.0.1.Final.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/hibernate-core-4.1.0.Final.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/hibernate-jpa-2.0-api-1.0.1.Final.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/jandex-1.0.3.Final.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/javassist-3.12.1.GA.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/javax.inject-1.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/jboss-logging-3.1.0.CR2.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/jboss-transaction-api_1.1_spec-1.0.0.Final.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/swing-layout-1.0.4.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/log4j-1.2.16.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-aop-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-asm-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-beans-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-context-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-core-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/spring-expression-3.0.6.RELEASE.jar abid
jarsigner -keystore myKeys -storepass pakistan lib/hsqldb.jar abid